### PR TITLE
Update Epiworld to v0.3.0

### LINKED ISSUE #8: Various Fixes
- [ ] Update EpiWorld (C++) to latest version.
- [ ] Fix testing CI actions (GitHub).

### PR DESCRIPTION
**Pull request by IsaccBarker**
Updated epiworld to v0.3.0 ([assoc. commit](https://github.com/UofUEpiBio/epiworld/commit/70d3d9199384e6fc275badd6f1f7d187fec572db)). Fixes #8 in part.

### CODE REVIEW

**Comment by gvegayon** [comment]
That was quick, @IsaccBarker! Let's see what happens with the CI on this one.

**Comment by gvegayon** [comment]
Also, were you able to run `README.qmd` with the new version?

**Comment by IsaccBarker** [comment]
Yes, I was (made sure before committing). I thought there was a GHCI action to test this?

**Comment by gvegayon** [comment]
We don't have a GHA to test that (README compiles). We should. I have one set up here: https://github.com/CDCgov/multisignal-epi-inference/. I'm merging this so we can move forward.

**Pull request merged**
